import QueryProvider from "../components/QueryProvider";
import "./globals.css";

export const metadata = {
  title: "Crypto Price Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
